// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiYZswHW6fiwXpkD-ZLCPlxpcX_yO6Ijo',
    appId: '1:963892032257:android:68abd51e32a8b080356100',
    messagingSenderId: '963892032257',
    projectId: 'cashheart-fd5de',
    storageBucket: 'cashheart-fd5de.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIBybow1tIOzb1ygIHG_VnqZLuGoG81zs',
    appId: '1:963892032257:ios:7c4a31b5a3c21db2356100',
    messagingSenderId: '963892032257',
    projectId: 'cashheart-fd5de',
    storageBucket: 'cashheart-fd5de.firebasestorage.app',
    androidClientId: '963892032257-me06p3g0kfkfvak7fhksrd7tef62crmr.apps.googleusercontent.com',
    iosClientId: '963892032257-0grrkatgce2vdb9cfjvnqgrbueo2gs25.apps.googleusercontent.com',
    iosBundleId: 'com.example.cashHeart',
  );

}